volumes:
  cerohumano-fs-volume:
    name: cerohumano-fs-volume
  cerohumano-db-volume:
    name: cerohumano-db-volume
  cerohumano-llm-volume:
    name: cerohumano-llm-volume

networks:
  cerohumano-network:
    name: cerohumano-network

x-logging: &formatted-logging
  driver: json-file
  options:
    tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
    max-size: '10m'
    max-file: '3'
    mode: 'non-blocking'
    max-buffer-size: '4m'

services:
  cerohumano-server:
    container_name: cerohumano_server
    image: cerohumano-server
    build:
      context: ./server
      dockerfile: ./services/server/Dockerfile
    tty: true
    restart: always
    depends_on:
      - cerohumano-db
    ports:
      - ${SERVER_PORT:-18777}:8000
    env_file:
      - .env
    logging: *formatted-logging
    volumes:
      - cerohumano-fs-volume:/data
    networks:
      - cerohumano-network

  cerohumano-generator:
    container_name: cerohumano_generator
    image: cerohumano-generator
    build:
      context: ./server
      dockerfile: ./services/generator/Dockerfile
    tty: true
    restart: always
    depends_on:
      - cerohumano-db
      - cerohumano-llm
      - cerohumano-server
    env_file:
      - .env
    logging: *formatted-logging
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - cerohumano-network

  cerohumano-db:
    container_name: cerohumano_db
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    restart: unless-stopped
    healthcheck:
      test: pg_isready --username=${DATABASE_USER} --dbname=${DATABASE_NAME}
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - cerohumano-db-volume:/var/lib/postgresql/data
    logging: *formatted-logging
    networks:
      - cerohumano-network

  cerohumano-llm:
    container_name: cerohumano_llm
    image: cerohumano-llm
    build:
      context: ./llm
      dockerfile: Dockerfile
    # ports:
    #   - 11434:11434
    volumes:
      - ./llm/models:/app/models
      - cerohumano-llm-volume:/root/.ollama
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # logging: *formatted-logging
    networks:
      - cerohumano-network
