import random


SEASONS = (
    'winter',
    'spring',
    'summer',
    'fall',
)
DAYTIMES = (
    'early morning',
    'dawn',
    'twilight',
    'sunrise',
    'morning',
    'midday',
    'noon',
    'afternoon',
    'evening',
    'golden hour',
    'sunset',
    'dusk',
    'night',
    'midnight',
)
LIGHTINGS = (
    'contrast lighting',
    'soft lighting',
    'normal lighting',
    'lit light',
    'dim light',
    'high key',
    'low key',
    'dramatic lighting',
)
IN_OUT_DOORS = (
    'indoor',
    'outdoor',
)
CLOTHES = (
    'casual outfit',
    'luxury',
    'avant garde',
    'editorial',
    'haute couture',
    'runway',
    'cyberpunk luxury',
    'techwear',
    'hypebeast',
    'oversized',
    'y2k streetwear',
    'athleisure',
    'skatecore',
    'goth',
    'cyberpunk',
    'whimsigoth',
    'grunge',
    'punk glam',
    'e girl',
    'dark academia',
    'coquette',
    'soft girl',
    'cottagecore',
    'kawaii',
    'fairycore',
    'pastel aesthetic',
    'y2k',
    '90s grunge',
    '70s retro',
    'vintage glam',
    'pin up',
    'old money',
    'clubwear',
    'baddie',
    'metallic',
    'bodycon',
    'euphoria high',
    'glitter glam',
    'boudoir',
    'minimalist lingerie',
    'loungewear',
    'sheer',
    'micro knit',
    'silk aesthetic',
)
MOODS = (
    'sensual',
    'mysterious',
    'playful',
    'confident',
    'dreamy',
    'edgy',
    'cozy',
    'provocative',
    'nostalgic',
    'energetic',
    'glamorous',
    'dominant',
    'rebellious',
    'elegant',
    'chill',
    'flirtatious',
    'melancholic',
    'bold',
    'innocent',
    'futuristic',
)
ENVIRONMENT_SETTINGS = (
    'bedroom',
    'luxury hotel suite',
    'neon lit alleyway',
    'minimalist living room',
    'rooftop at sunset',
    'sunlit garden',
    'mirrored dressing room',
    'industrial warehouse',
    'beachfront balcony',
    'vintage diner',
    'dimly lit lounge',
    'cozy coffee shop',
    'futuristic studio',
    'swimming pool edge',
    'underground parking',
    'coastal cliffside',
    'private jet interior',
    'art gallery',
    'urban tennis court',
    'marble bathroom',
)
PLACES = (
    'los angeles',
    'miami beach',
    'tokyo shibuya',
    'paris cafe',
    'ibiza beach club',
    'london underground',
    'new york rooftop',
    'milan fashion week',
    'las vegas strip',
    'bali resort',
    'seoul neon district',
    'berlin night club',
    'amalfi coast',
    'dubai marina',
    'amsterdam canals',
    'icelandic black beach',
    'kyoto bamboo forest',
    'monaco harbor',
    'rio de janeiro',
    'santorini caldera',
    'maldives',
)


ALL_CAPTION_CATEGORIES = (
    CLOTHES,
    DAYTIMES,
    ENVIRONMENT_SETTINGS,
    IN_OUT_DOORS,
    LIGHTINGS,
    MOODS,
    PLACES,
    SEASONS,
)


def pick_random_caption_settings():
    # 1. picking categories
    categories_amount = random.randint(5, len(ALL_CAPTION_CATEGORIES))
    categories = random.sample(ALL_CAPTION_CATEGORIES, categories_amount)

    # 2. picking one token from each chosen categories
    return [random.choice(category) for category in categories]

