"""empty message

Revision ID: bb10d55b20b2
Revises: e99fedb63eb2
Create Date: 2026-10-06 20:52:55.356782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb10d55b20b2'
down_revision: Union[str, Sequence[str], None] = 'e99fedb63eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cerohumanos', 'lora_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'cerohumanos', 'attachments', ['profile_picture_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cerohumanos', type_='foreignkey')
    op.alter_column('cerohumanos', 'lora_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
