"""empty message

Revision ID: e6afceb17dc7
Revises: f01808c39a03
Create Date: 2026-07-14 21:19:50.452473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6afceb17dc7'
down_revision: Union[str, Sequence[str], None] = 'f01808c39a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cerohumanos', 'attachments', ['profile_picture_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cerohumanos', type_='foreignkey')
    # ### end Alembic commands ###
